from alembic import command
from sqlalchemy import text

from app.core.database import engine
from tests.conftest import alembic_config


def test_migrations_create_every_table():
    with engine.connect() as connection:
        tables = set(connection.execute(text("SELECT tablename FROM pg_tables WHERE schemaname = 'public'")).scalars())
    assert {"users", "sessions", "budgets", "transactions", "consents", "audit_logs", "alembic_version"} <= tables


def test_models_and_migrations_do_not_drift():
    # Fails if a model changes without a matching migration (raises AutogenerateDiffsDetected).
    command.check(alembic_config())


def test_health_reports_database_ok_and_request_id(client):
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok", "database": "ok"}
    assert len(response.headers["X-Request-ID"]) == 32
